spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # MySQL8.0
    # url: jdbc:mysql://repo.emon.vip:3306/mybatisdb?serverTimeZone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    # MySQL5.7
    url: jdbc:mysql://repo.emon.vip:3306/mybatisdb?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123

mybatis-plus:
  # 设置MyBatis-Plus的全局配置
  global-config:
    db-config:
      # 表名统一前缀，默认情况下优先级比@TableName低
      table-prefix: mp_
      # 设置主键生成策略
      id-type: assign_id
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true # 默认true
  mapper-locations: classpath*:/mapper/**/*.xml # 默认位置
  # 配置类型别名所对应的包
  type-aliases-package: com.coding.mybatis.sbsmp.pojo
  # 扫描通用枚举包：非必须
  type-enums-package: com.coding.mybatis.sbsmp.enums



